### ISSUE TITLE
Cannot allocate vector of x size

### ISSUE THREAD

**Issue by hinckleyb** [chrisschuerz/SWATrunR#54]
Hey Chris,

I ran into this issue when I tried to run swatplusR on a rather large dataset. I'm running this on a computer with ~32 gigabytes of RAM on it. It's odd because the error message is smaller than the memory.limit allotted to R. When I run this code it fails and I get this error. If I rerun the code, it runs but gives odd output and is accompanied with a warning message "model.run folder already exists".

Can you give some insight into fixing this error, or am I best served rerunning swat and reducing my HRU's and Channels?

Thanks,
Brian

![image](https://user-images.githubusercontent.com/96082835/155207783-f151e7ca-2e30-4e7f-8df1-aec4ae5318c8.png)

**Comment by chrisschuerz** [comment]
Hi Brian,

yes it seems to me that you run out of RAM when the channel output file is read. You could check the file size (or at least get an idea about it) when you run the model from the TxtInOut folder and just see how large the channel output files are.

In my experience the size value that is printed in the error message is not really related to the memory limit. I think (not know! :)) that this is more related to how the function you use for reading in this case a `readr::read_*` function reads chunks of your file. In this case it was not able to read a chunk of that size because it ran out of memory. I had some situations where I wanted to read files of several GB and the error message said something about a vector of a few kB.

Sorry no solution for that but just my two cents on it.

**Comment by hinckleyb** [comment]
Thank you for the reply! I'll post again if we find a work around outside of using a bigger computer!

Brian
