### ISSUE TITLE
Can't find executable file

### ISSUE THREAD

**Issue by Daveldw** [chrisschuerz/SWATrunR#66]
Hi, chris
I want to run my own project, but I don't understand what is the "executable file".I didn't find anything in the installed folder and project folder. It's so nice of you if you can answer me this question.
Best wishes

**Comment by chrisschuerz** [comment]
Hey @Daveldw if you want to run simulations in your own project you need a folder that includes all SWAT files and a SWAT executable file. When you run SWAT e.g. from the SWAT+Editor it copies an .exe file into the folder (but I think removes it again after the simulation). So you can either copy the .exe file which is used in such a simulation and put it into your project folder (so that it is there permanently), or you can download an executable file (for SWAT2012 or SWAT+) [here](https://swat.tamu.edu/software/). 

After you put the .exe file into your project folder, you have to define the `project_path` in `run_swatplus()` in R that it points to your project folder. Let me know if you still have troubles.

**Comment by Daveldw** [comment]
> 

Hi chris, thank you for your patient answer!

I've read your article about calibration, and I have a question which I want to discuss (ask , actually :) ) with you.
You give a simple calibration method of dividing parameters into several panels, and put them in the model to see the outcome.
But when the model is big and complex, for example it needs about 3hrs to run model one time, it's impossible to model all these parameter combinations. So the automatic algorithm is quite important, which could easily realize in R because there are plenty of packages about that ( PSO, Bayes, etc.). But this still requires lots of time, because I need to iterate about 200 times if I want to get the best simulation.
I know that run_swatplus() provides parallel process which is so warm hearted! But often the automatic algorithm packages don't offer that convenient method. So I just want to know is there a way to solve this problem using parallel process? It would be so nice of you if you can answer that.

Best wishes!

**Comment by chrisschuerz** [comment]
Well I think in this case it really depends on the optimization algorithm you want to implement. If the algorithm or steps in the optimization can be run in parallel then you should use the parallellization of the optimizer. If each step of the optimization depends on the previous step (which is the case for several algorithms) then you cannot make use of parallelization. 

In general parallelization with any optimization algorithm may be tricky. I know that  @hzambran has been working on an optimization algorithm which uses parallelization and can run with SWAT+ model setups. He had a talk at the last SWAT conference. Just have a look [here](https://swat.tamu.edu/conferences/2023-aarhus/agenda/) and search for the talks of Rodrigo Marinao-Rivas and Mauricio Zambrano-Bigiarini. 

I hope his is helpful for your work!

**Comment by Daveldw** [comment]
Wow! That's amazing!

Thank you soooo much!
